### ISSUE TITLE
jaccard error

### ISSUE THREAD

**Issue by ZuseZ33** [DoktorBotti/JUnit-abschluss-1#3]
"jaccard a;b;c;d;e;f;g;h;i;j;h b;c;d;e;f", "0.500\n",
I guess it should be:
 "jaccard a;b;c;d;e;f;g;h;i;j b;c;d;e;f", "0.500\n",
to be true

**Comment by JoTJ** [comment]
no the first one contains "h" twice so one should be removed because "jaccard" is based on mathematic sets
;)

**Comment by ZuseZ33** [comment]
Shame on me, haven't seen that.
